name: Marketplace Release

on:
  push:
    tags:
      - "*-web-v*"
      - "*-native-v*"
      - "*-hybrid-v*"
      - "data-widgets-v*"
      - "atlas-core-v*"
      - "atlas-web-*-v*"

jobs:
  publish_release:
    name: "Marketplace Release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checking-out code"
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2
        with:
          submodules: false
      - name: "Defining Environment Variables"
        id: variables
        run: echo "::set-output name=tag::$(git tag --points-at HEAD)"
      - name: "Defining lerna scope"
        uses: jungwinter/split@c185fe95439c136a8788b7f700bd5275920d7109 # v1
        id: scope
        with:
          msg: "${{ steps.variables.outputs.tag }}"
          seperator: "-v"
      - name: "Defining node version"
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version-file: ".nvmrc"
      - name: "Installing dependencies"
        run: npm install
      - name: "Building native widgets and js actions"
        if: contains(steps.scope.outputs._0, '-native')
        run: npm run release:native
      - name: "Updating Native Mobile Resources project"
        if: contains(steps.scope.outputs._0, '-native')
        run: "npm run create-modules:native"
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_NAME: ${{ secrets.GH_NAME }}
          GH_PAT: ${{ secrets.GH_PAT }}
          TAG: ${{ steps.variables.outputs.tag }}
      - name: "Check changes and publish package ${{ steps.variables.outputs.tag }}"
        run: "npm run release:marketplace -- --scope '${{ steps.scope.outputs._0 }}'"
        env:
          MARKETPLACE_API_KEY: ${{ secrets.MARKETPLACE_API_KEY }}
          MARKETPLACE_USERNAME: ${{ secrets.MARKETPLACE_USERNAME }}
          TAG: ${{ steps.variables.outputs.tag }}
      - name: "Send workweixin notifier on successful"
        uses: jerray/work-weixin-notifier@5341bd2e4ee6e2a2abe410f1a63ace0fdffb4384
        with:
          key: ${{ secrets.WEIXIN_API_KEY }}
          type: text
          content:
            "Release Marketplace Release success while uploading version ${{ steps.scope.outputs._1 }} of package ${{
            steps.scope.outputs._0 }} to the marketplace.
            <https://github.com/${{ github.repository }}/releases/tag/${{ steps.variables.outputs.tag }}|More info..>"
          status: ${{ job.status }}
